version: '3'
services:
  frontend: 
    # container_name: projectmanager-frontend
    # restart: always
    build: ProjectManagerFrontend
    ports:
      - "4200:80"
    depends_on: 
      - backend
  backend:
    # container_name: projectmanager-backend
    # restart: always
    build: ProjectManagerBackend
    # volumes:
    #   - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    # container_name: "mongodb"
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_DATA_DIR=/data/db
    #   - MONGO_LOG_DIR=/dev/null
    # volumes:
    #   - ./data/db:/data/db